services:
  augur:
    ports:
      - "10001:10001" # Expose the debugpy port to the host
    # command: >
    #   sh -c "pip install --no-cache-dir debugpy && 
    #          python -m debugpy --wait-for-client --listen 0.0.0.0:5678 
    #          -m gunicorn --bind 0.0.0.0:5000 --workers=1 --threads=1 augur.server:app"